name: mosdef-study38
channels:
  - conda-forge
  - conda-forge/label/hoomd_dev
  - bioconda
dependencies:
  - constrainmol
  - ele
  - foyer=0.11.2
  - freud=2.6.2
  - gmso
  - gromacs=2020.6
  - gsd<2.9.0
  - h5py
  - jupyter
  - jinja2
  - lammps
  - matplotlib
  - mbuild=0.15.1
  - mdtraj
  - mosdef_cassandra
  - numpy
  - openmm>=7.6
  - packmol>=18
  - pandas
  - panedr
  - parmed>=3.4.3
  - pymbar=3.0.5
  - pytest
  - python=3.8
  - rdkit
  - scipy
  - seaborn
  - signac=1.7.0
  - signac-dashboard
  - signac-flow=0.20.0
  - unyt
